/**
 * Static product content for the site.
 *
 * Build and test numbers do NOT live here — they come from
 * `src/data/report.json`, generated by `make report` from a real run.
 * Never hand-write a status number into this file.
 */

export const project = {
  name: "Verdict",
  tagline: "Agentic resolution for information markets on Stellar",
  summary:
    "Binary markets settled by 8004-registered agents. Resolvers submit an outcome with evidence and a bond, are weighted by their on-chain track record, and are paid or slashed when the market finalises.",
  network: "Soroban · Stellar Testnet",
  repo: null as string | null,
};

export const nav = [
  { href: "/", label: "Overview" },
  { href: "/protocol", label: "Protocol" },
  { href: "/agents", label: "Agents" },
  { href: "/status", label: "Status" },
];

export const pitch = {
  problem:
    "Information markets settle in one of three ways: an admin decides, a price feed decides, or the crowd votes. The first is trusted, the second only works for prices, and the third is Sybil-shaped.",
  answer:
    "Verdict makes resolution an accountable job. Any agent registered on the 8004 Identity Registry can resolve a market by posting an outcome, the evidence behind it, and a bond. Being right earns a share of the fee. Being wrong costs the bond. Either way the result is written to the 8004 Reputation Registry, so the record follows the agent everywhere.",
  principle:
    "Influence comes from reputation, never from capital. Every resolver posts the same flat bond — weight is earned only by being right.",
};

export const properties = [
  {
    title: "Evidence is mandatory",
    body: "A submission without an evidence URI and its hash is rejected by the contract. Every resolution is auditable back to the sources the agent actually used.",
  },
  {
    title: "Reputation-weighted, not stake-weighted",
    body: "Submissions carry a 1.00×–3.00× weight derived from that agent's record inside Verdict. Bonds are flat, so buying influence is not possible.",
  },
  {
    title: "Portable track record",
    body: "Results are written to the 8004 Reputation Registry under the `verdict` tag. Any other protocol can read an agent's history without trusting us.",
  },
  {
    title: "Bonded and challengeable",
    body: "A tally is provisional until a challenge window passes. Anyone can challenge by posting a larger bond, which keeps resolvers honest between submission and finality.",
  },
  {
    title: "Parimutuel by design",
    body: "No pricing curve, no orderbook, no liquidity provider. The winning pool splits the losing pool. Fees are taken from the losing side only.",
  },
  {
    title: "Nothing silently strands",
    body: "A market with an empty side, no resolver submissions, or an exact weight tie voids rather than settling. Every stake refunds 1:1, every bond returns, no fee is taken — and voiding returns success, because an error would revert the state write and trap the escrow.",
  },
];

export const flow = [
  {
    step: "01",
    title: "Market opens",
    body: "A binary question is published with its resolution criteria and expected sources. The document is hashed on-chain, so the terms cannot change after people stake against them.",
  },
  {
    step: "02",
    title: "Positions are taken",
    body: "YES/NO stakes go into escrow in a SEP-41 token. Two pools, no pricing curve. Trading stops at close time.",
  },
  {
    step: "03",
    title: "Agents submit",
    body: "Registered agents post an outcome, an evidence document with its hash, and a flat bond. Ownership is checked against the 8004 Identity Registry — one submission per agent.",
  },
  {
    step: "04",
    title: "Weighted tally",
    body: "Each submission is weighted by its agent's Verdict record, snapshotted at submission time. The weighted majority becomes the provisional outcome and a challenge window opens.",
  },
  {
    step: "05",
    title: "Challenge or finalise",
    body: "Unchallenged, anyone can finalise once the window closes. Challenged, the market moves to the dispute resolver.",
  },
  {
    step: "06",
    title: "Settle",
    body: "Winners claim pro rata. Correct resolvers recover their bond plus a weight-proportional share of the fee. Wrong ones are slashed to the treasury. Every result is written to 8004.",
  },
];

export const states = [
  { name: "Open", desc: "Trading", trading: true },
  { name: "Resolving", desc: "Agents submit", trading: false },
  { name: "Tallied", desc: "Challenge window open", trading: false },
  { name: "Disputed", desc: "Awaiting dispute resolver", trading: false },
  { name: "Settled", desc: "Claims open", trading: false },
  { name: "Void", desc: "Refund 1:1, no fee", trading: false },
];

export const economics = [
  { k: "Pricing", v: "Parimutuel — the winning pool splits the losing pool" },
  { k: "Payout", v: "stake + stake × distributable / winning_pool" },
  { k: "Protocol fee", v: "2% of the losing pool only" },
  { k: "Fee split", v: "60% to correct resolvers, 40% to treasury" },
  { k: "Resolver bond", v: "Flat and identical for every agent" },
  { k: "Wrong resolver", v: "Bond slashed in full to the treasury" },
  { k: "Challenge bond", v: "2× the resolver bond" },
  { k: "Weight band", v: "1.00× (new or always wrong) → 3.00× (perfect record)" },
];

export const entrypoints = [
  {
    group: "Trading",
    fns: ["create_market", "bet", "close_market", "void_market", "claim", "refund"],
  },
  {
    group: "Resolution",
    fns: ["submit_outcome", "tally", "challenge", "resolve_dispute", "finalize", "settle_resolvers"],
  },
  {
    group: "Reads",
    fns: ["get_market", "get_pools", "get_position", "get_submissions", "get_challenge", "get_agent_stats", "get_weight", "quote_payout", "treasury_balance"],
  },
  {
    group: "Admin",
    fns: ["set_config", "set_registries", "set_dispute_resolver", "set_paused", "withdraw_fees"],
  },
];

export const invariants = [
  "A winner never receives less than their own stake.",
  "Total payouts never exceed escrow; rounding always floors toward the protocol.",
  "Economic terms are snapshotted per market at creation — config changes are never retroactive.",
  "Resolver weight is snapshotted into the submission and cannot be changed by later reputation.",
  "A void market takes no fee and returns every bond.",
  "Every state transition emits an event.",
];

export const registries = {
  source: "trionlabs/stellar-8004",
  sourceUrl: "https://github.com/trionlabs/stellar-8004",
  explorer: "https://stellar8004.com",
  contracts: [
    {
      name: "Identity Registry",
      testnet: "CDE3K4COIAGWNNJQQLL26SYI3KBJF5FUDHXG5FA6GYDJCG7T5V7FIWZH",
      use: "Agent existence and ownership checks on submission",
    },
    {
      name: "Reputation Registry",
      testnet: "CBZEAGIEI3HXMDRLF44KLQJQQOH6LCYWWSGJVSYQYQO2HQ6DDGZ7HT55",
      use: "Portable track record written on settlement",
    },
    {
      name: "Validation Registry",
      testnet: "CC5USZRO26MOIAVNYTTJDS63C2OBBLREOAOET4CPF2EZWO3YFKLMO3SL",
      use: "Not used in v1",
    },
  ],
};

export const deployment: {
  network: string;
  contractId: string;
  deployTx: string;
  token: string;
  deployedAt: string;
} | null = {
  network: "testnet",
  contractId: "CD75VOBNOPZQJ2ZLV5CE2JTIQFE6BFBJK2KNLA26JPXEH223L3RSLHO5",
  deployTx: "93752ea58e1a7cba7e7dd7c1d2d5284fbba7f9b9dbca2cf2b724b0f4c31f8515",
  token: "CBEJPXHJ3G3YENGGTNEYC6WAQFM6Q5JKRUIKV4AJ25KBWOQ7J6CVLPHU",
  deployedAt: "2026-08-21",
};

/**
 * A real market run end to end on testnet against the live 8004 registries.
 * Reproduce it with `./scripts/demo.sh`.
 */
export const demoRun = {
  marketId: 3,
  question: "Has the Stellar testnet passed ledger 4,295,051?",
  questionNote:
    "A deliberately boring question, and that is the point — checkable by anyone against a public endpoint, with no API key and no argument about what the right answer was.",
  stakes: [
    { who: "alice", side: "YES", amount: "60 VUSD" },
    { who: "bob", side: "NO", amount: "40 VUSD" },
  ],
  tally: { outcome: "YES", weightFor: 200, weightTotal: 300, submissions: 3 },
  settlement: {
    alicePayout: "99.2 VUSD from a 60 VUSD stake",
    treasury: "one slashed bond plus the protocol cut",
  },
  agents: [
    {
      id: 21,
      source: "stellar-ledger",
      call: "YES",
      correct: true,
      settled: "bond returned + 0.24 VUSD",
      stats: "1 correct / 0 wrong",
      nextWeight: "3.00\u00d7",
      onChainRecord: "+100",
    },
    {
      id: 22,
      source: "stellar-ledger",
      call: "YES",
      correct: true,
      settled: "bond returned + 0.24 VUSD",
      stats: "1 correct / 0 wrong",
      nextWeight: "3.00\u00d7",
      onChainRecord: "+100",
    },
    {
      id: 23,
      source: "contrarian (demo)",
      call: "NO",
      correct: false,
      settled: "10 VUSD bond slashed",
      stats: "0 correct / 1 wrong",
      nextWeight: "1.00\u00d7",
      onChainRecord: "\u2212100",
    },
  ],
  reputationReadback:
    'get_summary(agent_id, [verdict], "verdict", "") \u2192 #21 +100 \u00b7 #22 +100 \u00b7 #23 \u2212100',
};

/**
 * Nothing in the run above was decided by a human. Three separate processes
 * registered themselves, read the network, and concluded independently.
 */
export const agentRun = {
  intro:
    "Three independent processes, each holding its own 8004 identity and its own key. Nobody told them the answer \u2014 each read the network, formed a conclusion, wrote down its reasoning and staked a bond on it.",
  steps: [
    {
      title: "Mint an identity",
      body: "The agent registers itself on the 8004 Identity Registry and gets an id. Its registration metadata is embedded inline, so there is no profile page to keep alive.",
    },
    {
      title: "Find work",
      body: "It scans for markets that have closed to trading, are inside the resolve window, and that it has not already submitted to.",
    },
    {
      title: "Observe",
      body: "It reads the threshold out of the market's question and checks it against live Horizon data. The source reads the question \u2014 the answer is not wired into the agent.",
    },
    {
      title: "Write evidence",
      body: "Observation, reasoning and source URLs go into a document, hashed over canonical JSON so two agents seeing the same facts commit to the same hash.",
    },
    {
      title: "Submit and stake",
      body: "Outcome, evidence URI and hash go on-chain with a flat bond. From there the contract decides who was right, and the agent lives with it.",
    },
  ],
  evidence: {
    note: "Evidence is embedded in the submission as a base64 data URI, not hosted. It cannot rot behind a dead link or be edited after the fact \u2014 the hash on-chain commits to bytes anyone can decode straight out of the contract.",
    command: "pnpm exec tsx src/cli.ts verify 3 21",
    output: `market     #3
agent      #21
outcome    YES
weight     1.00x
hash       75ba69a6dbe03fb8fe1217ea1aa0c6811dea6e3bc2ec4d27c2afac4dbcf9f124
verified   true

--- evidence ---
{
  "agent": 21,
  "market": "3",
  "observed": {
    "closedAt": "2026-08-23T22:14:02Z",
    "latestLedger": 4300063,
    "threshold": 4295051
  },
  "outcome": 1,
  "reasoning": "Latest closed ledger is 4300063; the question asks whether the
                network passed 4295051. It did, so the outcome is YES.",
  "source": "stellar-ledger",
  "sources": ["https://horizon-testnet.stellar.org/ledgers?order=desc&limit=1"]
}`,
  },
  tie: {
    title: "A tie voids the market",
    body: "An earlier run ended with one agent on each side at equal weight. With no majority there is no defensible outcome, so the market voided: every stake refundable in full, every bond returned, no fee taken, and nothing recorded about who was right. Verified on testnet as market #2.",
  },
};

/**
 * Every branch of the state machine, exercised against the deployed contract on
 * testnet. Unit tests cover these too; this is the same behaviour with real
 * money, real 8004 calls and real network latency.
 */
export const coverage = [
  {
    market: 1,
    branch: "Settle",
    detail:
      "Two agents agree, the market finalises unchallenged, the winner claims and the correct resolvers are paid.",
  },
  {
    market: 2,
    branch: "Void on a tie",
    detail:
      "One agent per side at equal weight. No majority, so the market voids: bonds returned, no fee, nothing recorded about who was right.",
  },
  {
    market: 3,
    branch: "Agent-decided settle",
    detail:
      "Three independent agent processes, 200/300 to YES. The dissenter is slashed and drops to 1.00\u00d7; the other two reach 3.00\u00d7.",
  },
  {
    market: 4,
    branch: "Challenge and dispute",
    detail:
      "Only the contrarian submits, so the tally lands on the wrong answer. A challenger posts 2\u00d7 the bond, the dispute resolver flips the outcome, the challenger recovers its bond plus the reward, and the resolver is slashed a second time.",
  },
];

export const limitations = [
  {
    title: "Dispute resolution is centralised",
    body: "A challenged tally is decided by the curator. This is a trusted backstop. The resolver is a single configurable address so it can be pointed at a staked arbitration contract without touching the rest of the contract.",
  },
  {
    title: "Market creation is curated",
    body: "Anyone can trade and any registered agent can resolve, but only the curator opens markets. Permissionless creation needs spam control that is not in this version.",
  },
  {
    title: "Binary outcomes only",
    body: "Outcomes are typed as u32 throughout; a single runtime guard restricts them to two.",
  },
  {
    title: "Testnet only",
    body: "No mainnet deployment and no external audit yet. Builds are reproducible so a deployed wasm can be verified byte-for-byte against source.",
  },
];
