/**
 * Static product content for the site.
 *
 * Build and test numbers do NOT live here — they come from
 * `src/data/report.json`, generated by `make report` from a real run.
 * Never hand-write a status number into this file.
 */

export const project = {
  name: "Verdict",
  tagline: "Agentic resolution for information markets on Stellar",
  summary:
    "Binary markets settled by 8004-registered agents. Resolvers submit an outcome with evidence and a bond, are weighted by their on-chain track record, and are paid or slashed when the market finalises.",
  network: "Soroban · Stellar Testnet",
  repo: null as string | null,
};

export const nav = [
  { href: "/", label: "Overview" },
  { href: "/protocol", label: "Protocol" },
  { href: "/status", label: "Status" },
];

export const pitch = {
  problem:
    "Information markets settle in one of three ways: an admin decides, a price feed decides, or the crowd votes. The first is trusted, the second only works for prices, and the third is Sybil-shaped.",
  answer:
    "Verdict makes resolution an accountable job. Any agent registered on the 8004 Identity Registry can resolve a market by posting an outcome, the evidence behind it, and a bond. Being right earns a share of the fee. Being wrong costs the bond. Either way the result is written to the 8004 Reputation Registry, so the record follows the agent everywhere.",
  principle:
    "Influence comes from reputation, never from capital. Every resolver posts the same flat bond — weight is earned only by being right.",
};

export const properties = [
  {
    title: "Evidence is mandatory",
    body: "A submission without an evidence URI and its hash is rejected by the contract. Every resolution is auditable back to the sources the agent actually used.",
  },
  {
    title: "Reputation-weighted, not stake-weighted",
    body: "Submissions carry a 1.00×–3.00× weight derived from that agent's record inside Verdict. Bonds are flat, so buying influence is not possible.",
  },
  {
    title: "Portable track record",
    body: "Results are written to the 8004 Reputation Registry under the `verdict` tag. Any other protocol can read an agent's history without trusting us.",
  },
  {
    title: "Bonded and challengeable",
    body: "A tally is provisional until a challenge window passes. Anyone can challenge by posting a larger bond, which keeps resolvers honest between submission and finality.",
  },
  {
    title: "Parimutuel by design",
    body: "No pricing curve, no orderbook, no liquidity provider. The winning pool splits the losing pool. Fees are taken from the losing side only.",
  },
  {
    title: "Nothing silently strands",
    body: "A market with an empty side, or with no resolver submissions, voids rather than settling. Every stake refunds 1:1, every bond returns, no fee is taken.",
  },
];

export const flow = [
  {
    step: "01",
    title: "Market opens",
    body: "A binary question is published with its resolution criteria and expected sources. The document is hashed on-chain, so the terms cannot change after people stake against them.",
  },
  {
    step: "02",
    title: "Positions are taken",
    body: "YES/NO stakes go into escrow in a SEP-41 token. Two pools, no pricing curve. Trading stops at close time.",
  },
  {
    step: "03",
    title: "Agents submit",
    body: "Registered agents post an outcome, an evidence document with its hash, and a flat bond. Ownership is checked against the 8004 Identity Registry — one submission per agent.",
  },
  {
    step: "04",
    title: "Weighted tally",
    body: "Each submission is weighted by its agent's Verdict record, snapshotted at submission time. The weighted majority becomes the provisional outcome and a challenge window opens.",
  },
  {
    step: "05",
    title: "Challenge or finalise",
    body: "Unchallenged, anyone can finalise once the window closes. Challenged, the market moves to the dispute resolver.",
  },
  {
    step: "06",
    title: "Settle",
    body: "Winners claim pro rata. Correct resolvers recover their bond plus a weight-proportional share of the fee. Wrong ones are slashed to the treasury. Every result is written to 8004.",
  },
];

export const states = [
  { name: "Open", desc: "Trading", trading: true },
  { name: "Resolving", desc: "Agents submit", trading: false },
  { name: "Tallied", desc: "Challenge window open", trading: false },
  { name: "Disputed", desc: "Awaiting dispute resolver", trading: false },
  { name: "Settled", desc: "Claims open", trading: false },
  { name: "Void", desc: "Refund 1:1, no fee", trading: false },
];

export const economics = [
  { k: "Pricing", v: "Parimutuel — the winning pool splits the losing pool" },
  { k: "Payout", v: "stake + stake × distributable / winning_pool" },
  { k: "Protocol fee", v: "2% of the losing pool only" },
  { k: "Fee split", v: "60% to correct resolvers, 40% to treasury" },
  { k: "Resolver bond", v: "Flat and identical for every agent" },
  { k: "Wrong resolver", v: "Bond slashed in full to the treasury" },
  { k: "Challenge bond", v: "2× the resolver bond" },
  { k: "Weight band", v: "1.00× (new or always wrong) → 3.00× (perfect record)" },
];

export const entrypoints = [
  { group: "Trading", fns: ["create_market", "bet", "close_market", "claim", "refund"] },
  {
    group: "Resolution",
    fns: ["submit_outcome", "tally", "challenge", "resolve_dispute", "finalize", "settle_resolvers"],
  },
  {
    group: "Reads",
    fns: ["get_market", "get_pools", "get_position", "get_submissions", "get_tally", "get_agent_stats", "get_weight", "quote_payout"],
  },
  {
    group: "Admin",
    fns: ["set_config", "set_registries", "set_dispute_resolver", "pause", "withdraw_fees", "propose_upgrade"],
  },
];

export const invariants = [
  "A winner never receives less than their own stake.",
  "Total payouts never exceed escrow; rounding always floors toward the protocol.",
  "Economic terms are snapshotted per market at creation — config changes are never retroactive.",
  "Resolver weight is snapshotted into the submission and cannot be changed by later reputation.",
  "A void market takes no fee and returns every bond.",
  "Every state transition emits an event.",
];

export const registries = {
  source: "trionlabs/stellar-8004",
  sourceUrl: "https://github.com/trionlabs/stellar-8004",
  explorer: "https://stellar8004.com",
  contracts: [
    {
      name: "Identity Registry",
      testnet: "CDE3K4COIAGWNNJQQLL26SYI3KBJF5FUDHXG5FA6GYDJCG7T5V7FIWZH",
      use: "Agent existence and ownership checks on submission",
    },
    {
      name: "Reputation Registry",
      testnet: "CBZEAGIEI3HXMDRLF44KLQJQQOH6LCYWWSGJVSYQYQO2HQ6DDGZ7HT55",
      use: "Portable track record written on settlement",
    },
    {
      name: "Validation Registry",
      testnet: "CC5USZRO26MOIAVNYTTJDS63C2OBBLREOAOET4CPF2EZWO3YFKLMO3SL",
      use: "Not used in v1",
    },
  ],
};

/** Verdict's own deployment. Filled in when the contract goes to testnet. */
export const deployment: {
  network: string;
  contractId: string;
  wasmHash: string;
  deployedAt: string;
} | null = null;

/** Notable testnet transactions, appended as the demo flow is built. */
export const transactions: { label: string; hash: string }[] = [];

export const limitations = [
  {
    title: "Dispute resolution is centralised",
    body: "A challenged tally is decided by the curator. This is a trusted backstop. The resolver is a single configurable address so it can be pointed at a staked arbitration contract without touching the rest of the contract.",
  },
  {
    title: "Market creation is curated",
    body: "Anyone can trade and any registered agent can resolve, but only the curator opens markets. Permissionless creation needs spam control that is not in this version.",
  },
  {
    title: "Binary outcomes only",
    body: "Outcomes are typed as u32 throughout; a single runtime guard restricts them to two.",
  },
  {
    title: "Testnet only",
    body: "No mainnet deployment and no external audit yet. Builds are reproducible so a deployed wasm can be verified byte-for-byte against source.",
  },
];
